[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Daniel Silverstone <daniel.silverstone@codethink.co.uk>"]
edition = "2018"
[dependencies]
md5="0.7.0"
regex="1"
lazy_static="1.2"
permutohedron="0.2.4"
serde_json="1"
itertools="0.9"
either="1.5.0"